name: CI/CD Workflow

on:
  push:
    branches: [ dev-client ]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm run init

  run_linters:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint_project

  build:
    needs: run_linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: npm run build
